# Generated by Django 3.1.7 on 2021-03-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0015_complaint_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('reported', 'Reported'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('closed', 'Closed')], default='reported', max_length=15),
        ),
    ]
